/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LeaguesRouteImport } from './routes/leagues'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WatchSlugRouteImport } from './routes/watch.$slug'
import { Route as SportSlugRouteImport } from './routes/sport.$slug'
import { Route as CompetitionSlugRouteImport } from './routes/competition.$slug'
import { Route as AdminSportsRouteImport } from './routes/admin.sports'
import { Route as AdminMatchesRouteImport } from './routes/admin.matches'
import { Route as AdminCompetitionsRouteImport } from './routes/admin.competitions'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'

const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesRoute = LeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WatchSlugRoute = WatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SportSlugRoute = SportSlugRouteImport.update({
  id: '/sport/$slug',
  path: '/sport/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionSlugRoute = CompetitionSlugRouteImport.update({
  id: '/competition/$slug',
  path: '/competition/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSportsRoute = AdminSportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchesRoute = AdminMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompetitionsRoute = AdminCompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/leagues': typeof LeaguesRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upcoming': typeof UpcomingRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/sports': typeof AdminSportsRoute
  '/competition/$slug': typeof CompetitionSlugRoute
  '/sport/$slug': typeof SportSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/leagues': typeof LeaguesRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upcoming': typeof UpcomingRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/sports': typeof AdminSportsRoute
  '/competition/$slug': typeof CompetitionSlugRoute
  '/sport/$slug': typeof SportSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/leagues': typeof LeaguesRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upcoming': typeof UpcomingRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/sports': typeof AdminSportsRoute
  '/competition/$slug': typeof CompetitionSlugRoute
  '/sport/$slug': typeof SportSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/leagues'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/upcoming'
    | '/admin/ads'
    | '/admin/competitions'
    | '/admin/matches'
    | '/admin/sports'
    | '/competition/$slug'
    | '/sport/$slug'
    | '/watch/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/leagues'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/upcoming'
    | '/admin/ads'
    | '/admin/competitions'
    | '/admin/matches'
    | '/admin/sports'
    | '/competition/$slug'
    | '/sport/$slug'
    | '/watch/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/leagues'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/upcoming'
    | '/admin/ads'
    | '/admin/competitions'
    | '/admin/matches'
    | '/admin/sports'
    | '/competition/$slug'
    | '/sport/$slug'
    | '/watch/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  LeaguesRoute: typeof LeaguesRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UpcomingRoute: typeof UpcomingRoute
  CompetitionSlugRoute: typeof CompetitionSlugRoute
  SportSlugRoute: typeof SportSlugRoute
  WatchSlugRoute: typeof WatchSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues': {
      id: '/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/watch/$slug': {
      id: '/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof WatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sport/$slug': {
      id: '/sport/$slug'
      path: '/sport/$slug'
      fullPath: '/sport/$slug'
      preLoaderRoute: typeof SportSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition/$slug': {
      id: '/competition/$slug'
      path: '/competition/$slug'
      fullPath: '/competition/$slug'
      preLoaderRoute: typeof CompetitionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sports': {
      id: '/admin/sports'
      path: '/sports'
      fullPath: '/admin/sports'
      preLoaderRoute: typeof AdminSportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matches': {
      id: '/admin/matches'
      path: '/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AdminMatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/competitions': {
      id: '/admin/competitions'
      path: '/competitions'
      fullPath: '/admin/competitions'
      preLoaderRoute: typeof AdminCompetitionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminCompetitionsRoute: typeof AdminCompetitionsRoute
  AdminMatchesRoute: typeof AdminMatchesRoute
  AdminSportsRoute: typeof AdminSportsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminCompetitionsRoute: AdminCompetitionsRoute,
  AdminMatchesRoute: AdminMatchesRoute,
  AdminSportsRoute: AdminSportsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  LeaguesRoute: LeaguesRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UpcomingRoute: UpcomingRoute,
  CompetitionSlugRoute: CompetitionSlugRoute,
  SportSlugRoute: SportSlugRoute,
  WatchSlugRoute: WatchSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
